GetClothes/Controllers/ClothesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GetClothes.Data;
using GetClothes.Models;
using GetClothes.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace GetClothes.Controllers
{
    public class ClothesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationContext _db;

        public ClothesController(ApplicationContext db, ILogger<HomeController> logger)
        {
            _db = db;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string query)
        {
            List<Article> articles;
            if (string.IsNullOrEmpty(query))
            {
                articles = await _db.Articles.ToListAsync();
            }

            articles = await _db.Articles.Where(x => EF.Functions.Like(x.Title, $"%{query}%")).ToListAsync();
            List<ArticleViewModel> vm = new List<ArticleViewModel>();
            foreach (var article in articles)
            {
                var description = await _db.ArticleDescriptions.FirstOrDefaultAsync(x => x.ArticleId == article.Id);
                var image = await _db.ArticleImages.FirstOrDefaultAsync(x => x.ArticleId == article.Id);

                ArticleViewModel articleViewModel = new ArticleViewModel()
                {
                    Id = article.Id,
                    Size = description.Size,
                    Title = article.Title,
                    Color = description.Color,
                    Price = article.Price,
                    Other = description.Other,
                    Image = image.Image
                };
                vm.Add(articleViewModel);
            }
            return View(vm);
        }
    }
}

GetClothes/Controllers/HomeController.cs
using GetClothes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using GetClothes.Data;
using GetClothes.ViewModel;
using Microsoft.EntityFrameworkCore;

namespace GetClothes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationContext _db;
        public HomeController(ApplicationContext db,  ILogger<HomeController> logger)
        {
            _db = db;
            _logger = logger;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var articles = await _db.Articles.ToListAsync();
            List<ArticleViewModel> vm = new List<ArticleViewModel>();
            foreach (var article in articles)
            {
                var description = await _db.ArticleDescriptions.FirstOrDefaultAsync(x => x.ArticleId == article.Id);
                var image = await _db.ArticleImages.FirstOrDefaultAsync(x => x.ArticleId == article.Id);

                ArticleViewModel articleViewModel = new ArticleViewModel()
                {
                    Id = article.Id,
                    Size = description.Size,
                    Title = article.Title,
                    Color = description.Color,
                    Price = article.Price,
                    Other = description.Other,
                    Image = image.Image
                };
                vm.Add(articleViewModel);
            }
            return View(vm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> Subscriber(NewsletterSubscriber subscriber)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            await _db.Subscribers.AddAsync(subscriber);
           await _db.SaveChangesAsync();
           return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Question()
        {
            return View("support");
        }
        [HttpPost]
        public async Task<IActionResult> Question(Question question)
        {
            if (!ModelState.IsValid)
                BadRequest(question);

            await _db.Questions.AddAsync(question);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");


        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GetClothes/Views/Home/Index.cshtml
@model List<GetClothes.ViewModel.ArticleViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="uk">
 <head>
  <title>Get clothes</title>
  <meta charset = "utf-8">
  <link rel="stylesheet" href="market.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
 <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;600;700&display=swap" rel="stylesheet">
 </head>
 <body>

<header id="header" class="header">
	<div class="cont">
		<div class="nav">
			<a href="/Home"><img src="img/logo.png" alt="Get Clothes"></a>
			<form asp-controller="Clothes" asp-action="Index">
  				<input type="text" name="query" placeholder="Пошук...">
 				<button type="submit"></button>
			</form>
			<ul class="menu">
				<li>
					<a href="/Clothes">
					Асортимент
					</a>
				</li>
				<li>
					<a href="/Home/Question">
					Підтримка
					</a>
				</li>
				@*<li>
					<a href="#">
					Вхід
					</a>
				</li>*@
			</ul>
			@*<img src="img/cart.png" alt="Cart">*@
		</div>
		<div class="lghtel"></div>
		<div class="wear">
		<img src="img/img1.png" alt=" ">
		</div>
		<div class="wear1">
		<img src="img/img2.png" alt=" ">
		</div>
		
		<div class="rul" >
			<p2>Якісний одяг може бути дешевшим</p2>
			
		</div>
		<div class="info">
		<p3>Інтернет-магазин вжитого одягу. Одягайся модно, дбаючи про навколишнє середовище;)</p3>
		</div>
		
	</div>


</header>
		
<section id="list" class="list">
	<div class="cont">
		<div class="new">
			<p1>Новинки</p1>
		</div>
		<div class="naf">
            @foreach (var item in Model)
            {
                <a href="/Article?id=@item.Id"><div class="multmod">
                    <img class="poster" src="data:image/jpeg;base64,@(Convert.ToBase64String(item.Image))" alt=" ">
                    <p4>@item.Title</p4>
                    <p5>@item.Price uah</p5>
                </div></a>
            }
		</div>
	</div>
</section>

	

<footer id="form" class="form">
	<div class="cont">
        <div class="for">
            <form  asp-action="Subscriber" asp-controller="Home">
                <div class="fo">
                    <p6>Підпишись на розсилку</p6>
                    <p9>і першим отримуй інформацію про знижки і новинки</p9>
                
                    <div class="input">
                        <input type="text" placeholder="Введіть ім`я" name="Name" required class="name">
                        <input type="email" placeholder="E-mail" name="Email" required class="email">
               
                    </div>
				
                </div>
               <input type="submit" value="Підписатися"/>
			</form>
			<img src="img/line.png" alt=" ">
			<div class="fo">
				<p7>ЗВ'ЯЖІТЬСЯ З НАМИ</p7>
				<div class="input" >
					<img src="img/mail.png" alt=" ">
					<p8>illya.gaidai2001@gmail.com </p8>
					
				</div>
				<div class="input" >
					<img src="img/phone.png" alt=" ">
					<p8>+38 (066)-677-37-19 </p8>
				</div>
			</div>
		</div>	
		<div class="for1">
			<p10>Ми у соцмережах:</p10>
			<img src="img/faceb.png" alt=" ">
			<img src="img/inst.png" alt=" ">
			<img src="img/tel.png" alt=" ">
			<p11>©2021 GetClothes . All Rights Reserved.</p11>
		</div>
	</div>
</footer>
		
		
 </body>
</html>

GetClothes/Views/Home/support.cshtml
<!DOCTYPE html>
<html lang="uk">
 <head>
  <title>Підтримка</title>
  <meta charset = "utf-8">
  <link rel="stylesheet" href="~/market.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
 <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;600;700&display=swap" rel="stylesheet">
 </head>
 <body>
<header id="header" class="header">
	<div class="cont">
		<div class="nav">
			<a href="getclothes.html"><img src="~/img/logo.png" alt="Get Clothes"></a>
			<p7>Підтримка</p7>
		</div>
	</div>
</header>
<section id="form" class="form2">
	<div class="cont">
		<div class="for">
			<div class="fo">
				<p6>Як ми можемо вам допомогти?</p6>
				<form asp-action="Question" style="display: flex; flex-wrap: wrap" class="input">
					<input type="text" placeholder="Введіть ім`я" name="Name" required class="name">
					<input type="email" placeholder="E-mail" name="Email" required class="email">
					<input type="text" placeholder="Питання" name="Text" required class="email">

					<input type="submit" style="top: 7px;" value="Відправити" />
				</form>
				<!--<input type="text" placeholder="Задати запитання" name="Запитання" required class="question">
				<img src="img/send.png" alt=" ">-->
			</div>
			<img src="~/img/line.png" alt=" ">
			<div class="fo">
				<p7>ЗВ'ЯЖІТЬСЯ З НАМИ</p7>
				<div class="input" >
					<img src="~/img/mail.png" alt=" ">
					<p8>illya.gaidai2001@gmail.com </p8>
					
				</div>
				<div class="input" >
					<img src="~/img/phone.png" alt=" ">
					<p8>+38 (066)-677-37-19 </p8>
				</div>
			</div>
		</div>	

	</div>
</section>

<footer id="form" class="footquest">
	<div class="cont1">
		<popq>Популярні запитання</popq>
		<pq>Як я можу оплатити замовлення?</pq>
		<po>
			<ol>
				<li>Накладеним платежем.</li>
				<li>Оплатити онлайн.</li>
			</ol>
		</po>
		<img src="~/img/ln.png" alt=" ">
		<pq> Чи оригінальий товар?</pq>
		<po>Весь асортимент, який представлений у нас на сайті це ТІЛЬКИ ОРИГІНАЛ.</po>
	</div>
</footer>




 </body>
</html>